# Site Settings
baseurl: ""
url : "https://dot3kim.github.io/"

# Blog Settings
theme_settings :
  title : Dot3Kim
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Dot3 Kim
    description : 솔플 개발자
    experience :
      - start : 2022-06-08
        end : 2022-06-08
        experience : 둘리시스템
      - start : 2022-06-08
        end : 2022-06-08
        experience : 똥짜테크
      - start : 2022-06-08
        end : 2022-06-08
        experience : (주)길동시스템
    skills : 
      - skill : C#, .NET, WPF, WinForm
        value : 55  # Percent value
      - skill : Delphi
        value : 44  # Percent value
      - skill : Python
        value : 33  # Percent value
        
  # Icons
  icons :
    email: dot3kim@google.com # Full email address, e.g.
    linkedin:  # Full URL 
    github: dot3kim
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube: dot3kim
    facebook:
    instagram:

  # Disqus
  disqus_shortname : dot3

# Pagination
paginate: 15
#paginate_path: "blog/page:num"
paginate_path: "page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
